on:
  push:
    branches:
      - 'main'
      - 'releases/**'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: every day
        run: echo "This step will be run every time anything is pushed to this repo... I hope"
